= 表单规范
:toc:


== 基本理念
制作表单时，要有明确的目的：

* 我们为什么需要在这放一个表单，它是用来完成什么样的功能 / 目的。
* 为了完成这个功能，是不是必须要有一个表单。有没有可能通过其他方式来实现同样甚至更好的效果。
* 表单中出现的每一个字段，是否真的是必须的。例如我们可能能通过其他方式获取到这一信息，而不用用户自己去填写。

明确了上面的问题，而不是随随便便的放一个表单在页面上。因为**用户不喜欢填写表单**。 +
这些目的除了我们自己要清楚外，也要清楚地表达给用户。这样他们就能知道自己究竟在做什么、为什么要做这件事，也就能比较愿意做下去。

验证表单时，不要把用户当作提防对象、错误制造者。 +
对前端来说，验证表单的目的是引导客户填写正确的内容、完成提交。 +
要想象用户也是希望把内容填写正确的，并且在大多数情况下是能够把内容填写正确的（如果不能，那是我们的失职，要反思是不是我们做的不够友好、易用）。 +
基于上面的想法，来设计表单的提示信息和错误信息，这样才能给用户带来友好的体验。 +
滴水不漏、永远视输入是有错误的、把提交表单的人视为潜在的破坏者，那是后端应该做的事。 +

填写表单，是一个**交流**的过程。客户在和我们说话 —— 填写表单内容；我们也在跟客户说话 —— 提供提示信息和错误信息。 +
因此，要把握好时机和频率。不要打断用户的说话，也不要说的太少或太多。 +
面对不同的人，还要说不同的话：对有经验的使用者（例如在只有有经验的人才用得上的功能中），适当提供一些技术性强的提示；对小白使用者，则提供更易懂的说明。


== 表单内容设计

=== 字段分组
表单可分为字段和操作控件（提交、取消等）两部分。 +
对于大的表单，可以把字段根据业务逻辑划分为几个组。 +

* 把大任务划分为多个小任务，可以让用户填写时不那么累
* 划分为多个组，用户在填写时头脑也比较清晰。知道自己在填写哪部分内容、整个表单当前的填写进度是怎样的。
* 分组后，还能实现在不同组之间使用不同的字段样式与交互方式，更有针对性

=== 信息设计
对于每一个字段，我们可以向用户提供的信息包括：

字段名:: 用户正在填写什么内容
字段说明:: 这个字段是做什么的，以及对字段值的格式要求...
错误信息:: 当前字段值有哪些问题、如何修正...

不是所有字段都需要字段说明和错误信息。 +
如果所有人都知道这个字段应该是什么格式，以及出错的时候错误在哪里，那就不需要提供它们。

=== 交互设计
有字段不合法的情况禁止提交表单（可以考虑禁用提交按钮）。并在用户能看到的地方给予提示信息，提示用户修正表单中的错误，然后才能提交。 +
提示信息可能分放置地点：

* 提交按钮旁边
* 鼠标经过提交按钮时，通过 tooltip 显示（限桌面端）
* 在屏幕顶部以 position: fixed 的形式显示警告信息面板

字段说明可以在输入前或输入过程中显示

只在用户与字段产生过交互后显示错误信息。 +
例如一个必填字段，不要页面刚打开用户还什么都没做呢，就显示“此字段不能为空”。 +
对于文本框， 点击进去、什么都没输、然后就离开，也算是进行过交互。

表单刚载入时，提交按钮应处于启用状态，无论实际上是否有字段不合法（按照上一条，此时即使有字段不合法，也不应显示错误信息） 。 +
如果此时有字段不合法，那么点击提交按钮并不会真的提交表单，但会使得所有不合法的字段的错误信息被显示出来。 +

尽量用控件而不是文本框，例如选择日期的控件、选择地址的控件，因为用户会觉得使用控件来选择内容会比让他们自己像文本框里输入内容要好受一点。 +
不得不让用户自己输入内容时，根据要输入的内容的类型，调整文本框类型和输入法布局，以给用户的输入提供便利。


== 参考资料
https://material.google.com/patterns/errors.html[Android Material Design - Errors] +
除了给出表单设计的准则，还提供了非常详尽的实际案例和实现细节（例如在哪显示错误信息、甚至包括字体大小有多大...）。非常有用

关于如果显示表单错误信息的一些讨论：

* http://www.uxmatters.com/mt/archives/2015/11/error-messages-are-an-anti-pattern.php
* http://designmodo.com/ux-form-validation/
* https://ux.stackexchange.com/questions/26173/what-is-best-practice-for-designing-form-error-messages
* http://developer.telerik.com/featured/form-validation-right-mobile-applications/
* https://www.google.com.hk/search?q=ios+form+show+error+message
