= Form 改进（2016-08-31）
:toc:


此次整理、合并了以前未完成的多版 Form 文档。 +
新版表单类库和当前正在运行的版本比，有如下变化：

=== 字段通过验证的情况下，不再允许输出 message
之前允许这样做，主要是为了让 restoreValid 功能能够在返回合法值的同时，保留错误信息。 +
好让用户知道这个字段之前是有问题的，只不过现在是自动修正过来了。 +
不过现在想来，这样做其实没有什么必要。所以不再支持了。

之前还考虑过能不能把它用在像注册表单中的密码字段的情况：在验证通过的同时，返回这个密码的强度。 +
但这也是不合适的。在通过或不通过的情况下都需要生成这个强度信息，所以应该独立与验证过程，单独生成。

=== 支持按回车触发字段验证
对于支持的控件，监听用户的输入行为，当用户敲击回车时，和 onBlur 一样，也触发验证。 +
对于有 submit button 的表单，敲击回车时应该会自动触发提交顺便触发验证。 +
因此此功能主要针对没有 submit button 的表单。


=== 重新梳理、调整表单的提交流程


=== 不再强制要求 submit 返回 promise。现在有两种选择

. 直接返回提交结果。即同步完成提交。 +
  适用于不需要调用远程 API，或是远程 API 的执行结果不影响提交结果的提交行为。 +
  设置了 submitOnValid=true 的表单，很多都是这种类型的。虽然 submit 回调中也会执行 API 调用，但这个调用的结果并不会影响 form 的状态。

. 返回 promise（异步完成提交）

=== 表单 onSubmit 返回结果的意义发生了改变
原来 onSubmit 返回的是表单是否提交成功。 +
但其实表单类库并不关注它是否提交成功，它只关注是不是有字段不合法，好去修改各字段的状态。 +
所以变成了返回各字段的验证结果，如果没有验证结果，就什么都不返回即可。

=== Form 添加一个 submitOnValid 功能
每当 form valid 时，就触发 submit 回调。这样 form 就不需要 valid 这一种回调了。简化了逻辑。 +
因为原本的 form valid 回调在调用时有 values 和 prevValues 两个参数，所以合并后的 form submit 回调也变成了有两个参数。 +
原本 form valid 会在表单初始化时触发一次（如果初始化时所有字段都是合法的），现在在 submitOnValid=true 的情况下，onSubmit 也将会在初始化时触发一次。

经检查，目前所有使用了 valid 回调的地方，都可以顺利转换成使用 submit 回调，可以放心的弃用 valid 回调。
